title: Minimal theme
logo: /assets/img/logo.png
description:
<p align="center">
<a href="pdf/resume.pdf">Resume</a>
<a href="https://www.linkedin.com/in/supriya-s-017300197/">LinkedIn</a>
<a href="https://github.com/Supriya">Github</a>

<br>
I am studying on Data Science and Data Analytics
</br>
</p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
